ARG VERSION

FROM registry.fit2cloud.com/jumpserver/lion:${VERSION}-lite
ARG TARGETARCH

ARG DEPENDENCIES="                    \
        curl                          \
        iputils-ping                  \
        telnet                        \
        vim                           \
        wget"

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    set -ex \
    && apt-get update \
    && apt-get install -y --no-install-recommends ${DEPENDENCIES}